baseURL = "https://pigeon.life/"
languageCode = "en-gb"
title = "~backwardspy"
enableEmoji = true
contentPath = "content"

[markup]
  [markup.highlight]
    codeFences = true
    style = "murphy"

[params]
    sitename = "~backwardspy"
