baseURL = "https://pigeon.life/"
languageCode = "en-gb"
title = "~backwardspy"
theme = "elephants"
enableEmoji = true
pygmentsCodeFences = true
pygmentsStyle = "murphy"
contentPath = "content"

[params]
    sitename = "~backwardspy"
